name: PVPMaster
version: '${project.version}'
main: tech.lech2td.pvpmaster.PVPMaster
api-version: 1.19
depend: [ Multiverse-Core ]
authors: [ LeChocolatChaud ]
commands:
  pvpmaster:
    description: Root command for PVPMaster games.
    permission: pvpmaster.default
    permission-message: You have no permission to participate in PVPMaster games!
    aliases: pm
    usage: "See /<command> help"
permissions:
  pvpmaster.default:
    default: true
    description: All the basic permissions for one to play the game.
    children:
      pvpmaster.in: true
      pvpmaster.out: true
      pvpmaster.help: true
  pvpmaster.admin:
    default: op
    description: All the permissions for game admins.
    children:
      pvpmaster.start: true
      pvpmaster.end: true
      pvpmaster.clear: true
      pvpmaster.register: true
      pvpmaster.unregister: true